name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY_HOST: registry.cn-beijing.aliyuncs.com
      IMAGE_NAME: colinleefish/pentagon
    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Extract Tag Name
        id: get_tag
        run: |
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "IMAGE_FULL_NAME=${REGISTRY_HOST}/${IMAGE_NAME}" >> $GITHUB_ENV
      
      - name: Log into Image Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_HOST }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Tag Docker Image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ env.TAG_NAME }} .
          docker tag ${{ env.IMAGE_NAME }}:${{ env.TAG_NAME }} ${{ env.IMAGE_NAME }}:latest

      - name: Push Docker Image
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ env.TAG_NAME }}
          docker push ${{ env.IMAGE_NAME }}:latest
